#!/bin/bash
 

/Users/stephanie/abin/3dLME -prefix TravelingSubs -jobs 1         \
-model  "1"                                                  \
-ranEff 'Subj+Scanner+Day'                                   \
-ICC                                                         \
-dataTable                                                   \
Subj    Scanner        Day    InputFile                      \
s1    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    1        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    1        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/01_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s1    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    2        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    2        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/02_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s1    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    3        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    3        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/03_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s1    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    4        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    4        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/04_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s1    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    5        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    5        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/05_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s1    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    6        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    6        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/06_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s1    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    7        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    7        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/07_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s1    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V1000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s1    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V1000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s2    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V2000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s2    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V2000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s3    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V3000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s3    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V3000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s4    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V4000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s4    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V4000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s5    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V5000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s5    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V5000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s6    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V6000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s6    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V6000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s7    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V7000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s7    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V7000_2_bis_pcc__3mm_fconn_resl.nii.gz \
s8    8        1    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V8000_1_bis_pcc__3mm_fconn_resl.nii.gz \
s8    8        2    /Users/stephanie/Documents/data/traveling_subs/results_pcc_vox_unsm/08_V8000_2_bis_pcc__3mm_fconn_resl.nii.gz \



